source 'https://rubygems.org/'
gem 'rake'
gem 'selenium-webdriver'
gem 'cucumber', '~> 2.4.0'
gem 'capybara'
gem 'rspec-expectations'
gem 'rspec'
gem 'rubyntlm'
gem 'activesupport'
gem 'rest-client'
gem 'rspec_junit_formatter'
gem 'rubyzip'
gem 'nori'
gem 'hashie'
gem 'tzinfo-data'
gem 'pdf-inspector'
gem 'pdf-reader'
gem 'clipboard'
gem 'byebug'
gem 'parallel_tests', '2.14.2'
gem 'net-sftp'
gem 'report_builder'
gem 'ruby-oci8'
gem 'activerecord'
gem 'activerecord-oracle_enhanced-adapter'
gem 'xmldsig'
gem 'countries'
gem 'savon', '~> 2.0'